export default {
    translations: {
        welcome: "Hello, i'm Myintelli",
        Menu: {
          dashboard: 'Home',
          times: 'Times',
          shifts: 'Shifts',
          permits: 'Permits',
          Setting: 'Setting'
        },
        General: {
            date: "Date",
            done: "Done",
            save: "Save",
            hour: "Hour",
            search: "Search",
            notResult: "Without results",
            close: "Close",
            loading: "Loading...",
            months: {
              jan: "January",
              feb: "February",
              mar: "March",
              apr: "April",
              may: "May",
              jun: "June",
              july: "July",
              aug: "August",
              sept: "September",
              oct: "October",
              nov: "November",
              dec: "December",
            },
            monthsAbv: {
              0: "Jan",
              1: "Feb",
              2: "Mar",
              3: "Apr",
              4: "May",
              5: "Jun",
              6: "Jul",
              7: "Aug",
              8: "Sep",
              9: "Oct",
              10: "Nov",
              11: "Dec",
            },
            daysAbv: {
              0: "Sun",
              1: "Mon",
              2: "Tues",
              3: "Wed",
              4: "Thurs",
              5: "Fri",
              6: "Sat",
            },
            in: 'In',
            out: 'Out',
            fileSizeExceeded: "File size exceeded (20Mb)",
            hourIn: 'Hour in',
            hourOut: 'Hour out'
        },
        Configuration: {
            changePassword: "Change password",
            currentPassword: "Current password",
            newPassword: "New password",
            validationPassword: "Enter the password again",
            FnLn1: "FIRST_NAME LAST_NAME",
            FnLn1Ln2: "FIRST_NAME LAST_NAME SECOND_LAST_NAME",
            FnMnLn1Ln2: "FIRST_NAME MIDDLE_NAME LAST_NAME SECOND_LAST_NAME",
            FnMnLn1: "FIRST_NAME MIDDLE_NAME LAST_NAME",
            Ln1Fn: "LAST_NAME FIRST_NAME",
            Ln1Ln2Fn: "LAST_NAME SECOND_LAST_NAME FIRST_NAME",
            Ln1Ln2FnMn: "LAST_NAME SECOND_LAST_NAME FIRST_NAME MIDDLE_NAME",
            Ln1FnMn: "LAST_NAME FIRST_NAME MIDDLE_NAME",
            timeZone: "Time zome",
            eventTime: "Event time",
            formatDate: "Format date",
            formatHour: "Format hour",
            formatNumber: "Format numeric",
            formatName: "Format Name",
            theme: "Theme",
            notMatchPassword: "Password do not match",
            timeLocal: "LOCAL TIME",
            timeEvent: "EVENT TIME",
            "YYYY-MM-DD": "YYYY-MM-DD",
            "DD-MM-YYYY": "DD-MM-YYYY",
            "YYYY/MM/DD": "YYYY/MM/DD",
            "DD/MM/YYYY": "DD/MM/YYYY",
            "MM-DD-YYYY":"MM-DD-YYYY",
            "MM/DD/YYYY":"MM/DD/YYYY",
            kilometres: "Kilometres",
            miles: "Miles",
        },
        PermissionError: {
            403: "Operation not allowed",
        },
        Common: {
            languageSelect: "Select a language",
            configTitle: "Configuration",
            serverInput: "Server url",
            user: "User",
            save: "Save",
            close: "Close",
            restore: "Restore",
            languageTitle: "Language",
            restorePassword: "Password",
            forgotPassword: "Forgot password?",
            copyright: "Copyright © Intelli Next",
            successTitle: "Successful operation",
            savedSuccess: "Saved successfully",
            errorTitle: "Error",
            passwordIncorrect: "Password invalid",
            darkTitle: "Dark",
            lightTitle: "Light",
            passwordResetedSuccesfully: "Password reseted succesfully.",
            recoverySuccess: "An email with the current password was sent",
            devices: "Devices",
            logout: "Logout",
            search: "Search",
            waiting: "Waiting",
            updateTitle: "Update successful",
            uploadedRegister: "Information updated successfully",
            userError: "Incorrect user or password",
            notFoundItems: "Items not found",
            titleFilters: "Filters",
            accept: "Accept",
            cancel: "Cancel",
            support: "Technical support",
            server: "Server",
            device: "Device",
            formatDate: "Format date",
            formatHour: "Format hour",
            formatNumber: "Format number",
            formatLength: "Format length",
            formatTemperature: "Format temperature",
            timeZone: "Time zone",
            about: "About",
            yes: "Yes",
            no: "No",
            logOut: "Cerrar sesión",
            sureLogOut: "Are you sure you want to Log out?",
            settings: "Settings",
            notifications: "Notifications",
            other: 'Other',
            urlserver: 'URL server',
            time: 'Times',
            informationTurn: 'Shift information',
            alert: 'Alert',
            comingSoon: 'Available soon',
            inConstruction: 'Under construction',
            today: 'Today',
            notFaceDetected:"Not face detected",
            permissionDetails: 'Permit details',
            permissions: 'Permits',
            timelogs:"Timelogs",
            selectedTypePerson: 'Select Person type',
            schedules: 'Shifts',
            titleConfirm: 'Confirm to delete',
            confirmDelete: '¿Are you sure to delete?',
            deletedSuccess: 'Deleted successfully',
            now: 'Now',
            warning: "Warning",
            uploadedRegister: "Succesful update",
            see: 'See',
            details: 'Details',
            punch: 'Punch',
            punchesHistory: 'Punches History',
            successTimelogNew : "Punch success",
            later: "Ask me later",
            warnings: {
              notActiveGPS: "GPS is not active",
              notLocationGet: "Location could not be obtained",
              locationMessage: "You are not authorized to obtain the location",
              notPermissionCamera: "You do not have the permissions to use the camera",
              notPermissionGPS: "You do not have the permissions to use geolocation"
            },
            permission:{
              cameraTitle: "Permissions to use the camera",
              cameraMessage: "To perform this operation requires the use of the camera",
              gpsTitle: "Permissions to use the geolocation",
              gpsMessage: "To perform this operation requires the use of the location"
            },
            delete: 'DELETE',
            mainServer: 'Main server',
            notTimelog:"Timelogs not found"
        },
        Login: {
            email: "E-Mail:",
            placeholderEmail: "Enter yor E-Mail",
            invalidEmail: "Invalid E-Mail",
            placeholderPassword: "Enter your Password",
            password: "Password:",
            signIn: "Sign In",
        },
        Errors: {
            user_blocked: "User is blocked, try to recover password",
            userError: "Incorrect user or password",
            disabledUser: "The user is inactive",
            userBlocked: "User is blocked, try to recover password",
            tokenExpired: "Session has expired",
            invalidPassword: "Invalid password",
            serverDown: "Connection failed!",
            notDeletedEntity: 'Entity could not be eliminated because they were related to one or more elements',
            INVALID_DATE_IN: "Invalid Date - End date prior to the initial",
            ENTITY_NOT_FOUND: "Entity was not found",
            ENTITY_DONT_HAVE_CONTRACT: "Entity does not have a contract",
            INVALID_DATE_FOR_PERIOD: "Closed payroll period",
            INVALID_DATE_ENTITY_HAVE_PERMISSION: "The entity already has a permit for indicated date",
            INVALID_DATE_ENTITY_HAVE_SCHEDULE: "The entity already has a schedule for the indicated date",
            personExistPhoto: "Person photo exits",
            personPhotoNotBelongTo: "Person photo not belong to",
            personPhotoThereAreNoFaces: "Person photo there are not faces",
            personPhotoMoreThanOneElementExits: "Person photo more than one faces exits",
            invalid: "Error invalid"
        },
        FormErrors: {
            if111: "Field required",
            if112: "Field unique",
            if112B: "The registry is being used",
            if113: "Type field numeric",
            if114: "Maximum length exceeded",
            if115: "Minimun length not exceeded",
            if116: "Invalid E-Mail",
            if117: "Type field array",
            if118: "Ivalid value",
            if119: "Type field string",
            if120: "Already registered",
            if121: "Field must be integer",
            if122: "The structure must be a door or an access control",
            if123: "Blanks are not allowed",
            if124: "The structure must be to allow parking",
            if125: "Passwords entered do not match",
            if126: "Ivalid URL",
            if130: "The new added type already exists for the person",
            if132: "Dates/hours exceed range",
            if404: "Field does not exist",
            STATUS_CONFLICT:
              "Structure type organizational not can be contain structure fisic",
            if492:
              "He can not be a logical organizacional, because he has devices assigned",
            if133: "Still has 1 unassigned position",
            if134: "Quantity must be greater than 0",
            if135: "Invalid reCaptcha",
            dateOutBeforeDateIn: "Final date cannot start before the initial date",
            dateInBeforeNow: "Initial date cannot be greater than today",
            dateVistBeforeNow: "Visit date cannot be before today",
            hourVistBeforeNow: "Hour cannot be before than hour",
            datesOutOfInitialRange: "Dates/hours exceed range",
        },
        User: {
            user: 'User',
            fullName: 'Full name',
            dni: 'DNI',
            email: 'E-Mail',
            cel: 'Phone',
            dataNotRegistered: 'DATA NOT REGISTERED',
            position: "Position",
            job: "Job",
            localization: "Localization",
            name: "Name",
            active: 'Active',
            activate: 'Activate',
            profilePicture: 'Profile picture',
            enrollFace: 'Enroll face',
            personalInformation: 'Personal information'
        },
        ChangePassword: {
            currentPassword: "Current password",
            newPassword: "New password",
            validationPassword: "Enter the password again",
        },
        Support: {
            email: 'E-Mail:',
            cellphones: 'Phone:',
            userManual: 'User manual:',
            address: 'Address:'
        },
        Device: {
            device: "Device:",
            key: 'Key:',
            os: 'Operating system',
            enroll: 'Enroll',
            enrolled: 'Enrolled',
        },
        Vehicle: {
            vehicle_plate: "Plate",
        },
        EventTask: {
            text_to_send: "Text to send",
            eventTypeCommon: "Common",
            // Paginas
            event: "Event",
            actions: "Actions",
            newAction: "New Action",
    
            // Modulos
            general: "General",
            access_control: "Access Control",
            visits: "Visitors",
            devices: "Devices",
            users: "Users",
            notifications: "Notifications",
            system: "Systems",
            time_attendance: "Time attendance",
    
            // Etiquetas/Placeholders
            event_name: "Event name",
            type_event_monitor: "What type of event do you want to monitor?",
            want_monitor: "What do you want to monitor?",
            select_type_filters: "Select the types of filters",
            select_module: "Select the module",
            type_action_do: "What type of action do you want to take?",
            select_parameters: "Select action parameters",
    
            // Eventos/Acciones
            ip: "Ip direction",
            action_scheduled: "Action Scheduled",
            scheduled_action: "Action scheduled",
            timelog: "Timelog",
            timelog_ac_accepted: "Timelog Verified",
            timelog_ta_accepted: "Timelog Verified",
            inTimeLog: "IN TIMELOG",
            outTimeLog: "OUT TIMELOG",
            inAndOutTimelog: "TIMELOG IN/OUT",
            disabledTimelog: "DISABLED TIMELOG",
            firstTimeLog: "FIRST TIMELOG",
            timelog_ac_not_verified: "Not Verified Timelog",
            timelog_ta_not_verified: "Not Verified Timelog",
            invalidTimelog: "INVALID TIMELOG",
            delayTimeLog: "DELAY TIMELOG",
            open_exit_button: "Opening with Exit Button",
            access_scheduled: "Access Schedule",
            scheduled_access: "Access Schedule",
            change_status_door_remote: "Remote Door Status Change",
            change_status_door_manual: "Manual Door Status Change",
            visit_new: "New Visit",
            visit_new_scheduled: "New Scheduled Visit",
            visit_closed: "Closed Visit",
            visit_change_status_scheduled: "Change of Status in Scheduled Visit",
            change_access_profile_persons: "Change people access profile",
            change_access_profile_vehicles: "Change vehicle access profile",
            add_to_blacklist: "Add to blacklist",
            remove_from_blacklist: "Remove from blacklist",
            connection_change: "Change Connection",
            user_login: "User Login",
            user_creation: "User Creation",
            user_blocked: "User blocked",
            password_change: "Change of Password",
            reports: "Reports",
            open_door: "Open Doors",
            close_door: "Closed Doors",
            lock_door: "Lock Doors",
            access_scheduled_enabled: "Enable Access Schedules",
            access_scheduled_disabled: "Disable Access Schedules",
            inactivate_person: "Inactivate people",
            activate_person: "Activate people",
            inactivate_vehicles: "Inactivate vehicles",
            activate_vehicles: "Activate vehicles",
            change_access_role: "Change Access Profile",
            persons_vehicles_disabled: "Disable Person / Vehicles",
            inactivate_registration_station: "Inactivate Workstations",
            activate_registration_station: "Activate Workstations",
            blacklist_goto: "Go to Blacklist",
            inactivate_device: "Inactivate devices",
            activate_device: "Activate devices",
            alerts: "Alerts",
            widgets: "Widgets",
            text_messages: "Text Messages",
            email_messages: "Mail Messages",
            plans: "Plans",
            battery_status_change: "Battery status change",
    
            // Filtros y Parámetros
            all_person: "All Persons",
            all_vehicle: "All Vehicle",
            entities: "Persons",
            entity: "Entity",
            entities_types: "Persons types",
            device: "Device",
            structures: "Structures",
            time: "Time",
            vehicles: "Vehicles",
            vehicle_type: "Vehicle type",
            biometric_models: "Biometric models",
            verification_modes: "Verification modes",
            start: "Start",
            end: "End",
            start_end: "In the moment of?",
            user: "User",
            visitants: "Visitants",
            visitors: "Visitors",
            visited: "Visited",
            access_roles: "Access profile",
            work_stations: "Workstations",
            report_templates: "Report templates",
            execution_time: "Execution time",
            weekdays: "Weekdays",
            devices_types: "Types of devices",
            device_status: "Device status",
            door_status: "State of doors",
            scheduled_visit_status: "Scheduled visit status",
            closing_mode_status: "Closing mode",
            connected: "Connected",
            disconnected: "Disconnected",
            open: "Open",
            close: "Close",
            lock: "Lock",
            executed: "Executed",
            cancelled: "Cancelled",
            automatic: "Automatic",
            manual: "Manual",
            report_templates: "Report templates",
            user_defined: "User defined",
            emails: "Emails",
            emailsPlaceholder: "example@email.com",
            recurrence_value: "Recurrence value",
            text_messaging_templates: "SMS templates",
            // text_messaging_templates: 'Text Messaging Templates',
            based_on_event: "Based event",
            access_types: "Access types",
            verification_results: "Verification results",
            persons_groups: "Persons groups",
            devices_groups: "Devices groups",
            vehicles_groups: "Vehicles groups",
            battery_status: "Battery Status",
            based_event: "Based event",
            create_update_user: "User modifications",
    
            // Campos
            field_in_date: "Start date",
            field_out_date: "Ending date ",
            field_in_hour: "Start time",
            field_out_hour: "Ending time",
            field_status: "Status",
            field_event_name: "Event name",
            field_settings_type: "Settings type",
            field_supervise: "Supervising",
            field_filters: "Filters",
            field_entities: "Entities",
            field_entities_types: "Persons types",
            field_devices: "Devices",
            field_structures: "Structures",
            field_dow: "Days of week",
            field_in_hour: "Start time",
            field_out_hour: "End time",
            field_status: "Status",
            field_vehicles: "Vehicles",
            field_plate: "plate",
            field_users: "Users",
            field_visitants: "Visitants",
            field_devices_models_biometrics: "Models biometrics",
            field_verification_modes: "Verification modes",
            field_access_scheduled: "Access scheduled",
            field_start_end: "In the moment of?",
            field_access_roles: "Access scheduled",
            field_work_stations: "Workstations",
            field_execute_hour: "Execution time",
            field_device_types: "Devices types",
            field_access_type: "Access types",
            field_visiteds: "Visited",
            field_verification_result: "Verification Result",
            field_vehicles_types: "Vehicles types",
            field_filter_status: "Devices status",
            field_common_action: "Common action",
            field_module: "Module",
            field_icons_groups: "Icons groups",
            field_entities_groups: "Persons groups",
            field_devices_groups: "Devices groups",
            field_vehicles_groups: "Vehicles groups",
            field_based_on_event: "Based on event",
            field_repetitions: "Repetitions",
            field_recurrence: "Recurrence",
            field_parameters: "Parameters",
            field_phones: "Phones",
            field_emails: "Emails",
            field_time_delay: "Delay time",
            field_access_profiles: "Access Profiles",
            field_time_hour: "Hour",
            field_content_text: "Contained text",
            field_id_text_template: "Id text template",
    
            // triggered_at: 'Event time',
            // event_description: 'Event description',
            eventTypes: "Event type",
            // eventAction: 'Action',
            // eventHeld: 'Action performed',
            persons_event: "Select the involved persons",
            // devices_event: 'Devices',
            // device: 'Device',
            // structure: 'Structure',
            // settingsTypeIn: 'Since',
            // settingsTypeOut: 'Until',
            // type: 'Type',
            // category: 'Category',
            // typeNotification: 'NOTIFICATION TYPE',
            // actionDevices: 'Actions devices',
            // sendType: 'Priority send',
            // email: 'Emails',
            // phone: 'Phones',
            // hourAction: 'Hour send',
            // status: 'Status',
            // sendMoment: 'SEND AT THE MOMENT',
            // visitTimelogs: 'VISITS TIMELOGS',
            // sendSpecificTime: 'SEND IN A SPECIFIC TIME',
            // notificationBar: 'NOTIFICATION IN THE SUPERIOR BAR',
            // alertMessage: 'Alert message',
            // simpleNotification: 'SIMPLE NOTIFICATION',
            // activeAlarm: 'ACTIVE ALARM',
            // turnOnLight: 'TURN ON LIGHT',
            // turnOffLight: 'TURN OFF LIGHT',
            // sendEmail: 'SEND EMAIL',
            // sendSms: 'SEND SMS',
            // openDoor: 'OPEN DOOR',
            // widgetNotification: 'WIDGET NOTIFICATION',
            // soundedAlarm: 'INTRUSION IN AREA',
            // anyone: 'ANYONE',
            // emergencyLight: 'EMERGENCY LIGHT',
            // nightLight: 'NIGHT LIGHT',
            // backupLight: 'BACKUP LIGHT',
            // Entities_types: 'Types person',
            // emails: 'Emails',
            phones: "Phones",
            // dashboardTimelogs: 'DASHBOARD ACCESS CONTROL',
            // dashboardVisit: 'DASHBOARD GUEST ',
    
            createOrUpdateUser: {
              2: "NEW USER",
              3: "UPDATE USER",
            },
    
            //LIST
            label_module: "Module",
            label_event_type: "Event type",
            label_supervising: "supervising",
            label_filters: "Filters",
            label_parameters: "Parameters",
            label_event_action: "Action",
            label_structures: "Structures",
            label_devices: "Devices",
            label_devices_models: "Devices models",
            label_not_has_elements: "Not has elements",
            infoEvent: "Event information",
            infoActions: "Event actions",
            infoAction: "Action information",
            recurenceDaily: "Daily",
            recurenceWeekly: "Weekly",
            label_execute_time: "Execution time",
            label_minutes: "Minutes",
            label_elements: "Elements",
            label_select_recurrence: "Recurrence",
            label_repetitions: "Repetitions",
    
            label_async_entities: "Which people?",
            label_async_entities_types: "What are the types of people?",
            label_async_vehicles: "Which vehicles?",
            label_async_vehicles_types: "What are the types of vehicles?",
            label_async_access_scheduled: "What access schedule?",
            label_async_access_profiles: "What access profiles?",
            label_async_work_stations: "In which workstations?",
            label_async_users: "Which users?",
            label_async_visitants: "Which visitors?",
            label_async_Visiteds: "Which ones visited?",
            label_async_devices: "On what devices?",
            label_async_content_report:
              "What type of content will the report carry?",
            label_async_content_text:
              "What type of content will the message carry?",
            label_async_persons_groups: "In which group of people?",
            label_async_devices_groups: "In which group of devices?",
            label_async_vehicles_groups: "In which group of vehicles?",
            label_devices_types: "What are the types of devices?",
            label_devices_models: "What device models?",
            label_access_types: "What are the types of access?",
            label_verifications_modes: "Select verification modes",
            label_verifications_result: "Select the verification result",
            label_close_modes: "Define the way of closing the visit",
            label_what_time: "At what time?",
            label_defined_status: "Define the state",
            label_set_time: "When it occurs between",
            label_structure_event: "In what structures?",
            label_structure_action: "In what structures?",
            label_recurrence: "Recurrence value",
            limitActions: "Cannot delete, minimum limit of 1 action per event",
            visit_timelogs: "Visitants timelogs",
            plan_notification: "Plan notification",
            change_status_message:
              "Are you sure you want to change the status del registro?",
            change_status: "Change status",
    
            //Items
            executeTime: {
              1: "Righ now",
              2: "Delay",
              3: "Specific",
            },
            recurrenceType: {
              1: "Diary",
              2: "Weekly",
            },
            result: {
              0: "Successful",
              1: "Invalid",
            },
            495: "Can't deleted a event conmon",
        },
        DetailTimelog: {
          title:"Punch details",
          in: "In",
          out: "Out",
          verified: "Verified",
          notVerified: "Unverified",
          sendTimelog: "SEND",
          cancelTimelog: "Cancel",
          turn: 'Shift',
          localization: 'Localization',
          job: 'Job',
          hour: 'Hour',
          timelog:'Timelog'
        },
        Turn: {
          week: 'W',
          biweekly: 'B',
          monthly: 'M',
          date: 'Date',
          turn: 'Shift',
          turns: 'Shifts',
          hour: 'Hours',
          hours: 'Hours',
          localization: 'Localization',
          job: 'Job',
          since: "Since",
          until: "Until",
          unscheduled: 'Unscheduled',
          permission: "Permit",
          Files: "Files",
          notTurn: "Shift not found"
        },
        Permission: {
          level1: "APPROVED",
          level2: "REJECTED",
          level3: "VERIFIED",
          level4: "ON REQUEST",
          level5: "PENDING",
          level6: "FLOATING",
          type: 'Type',
          hour: 'Hour',
          description: "Description",
          status: "Status",
          Files: "Files",
          date: 'Date',
          history: "History",
          type_parcial: "PARTIAL",
          type_daily: "DAILY",
          newPermission: 'New permit',
          editPermission: 'Edit permit',
          dateIn: 'Start date',
          dateOut: 'End date',
          timeIn: 'Start time',
          timeOut: 'End time',
          id_novelty_permission: 'Permit',
          date_time_in: 'Initial date',
          date_time_out: "Final date",
          time_in: "Start time",
          time_out: "End time",
          notPermission: "Permissions not found"
        },
        Times: {
          title: 'Times',
          withoutPunch: 'Without punch',
          notScheduled: "Unscheduled",
          resumeHours: "Resume times",
          hoursScheduled: "Hours scheduled",
          hoursWorking: "Hours worked",
          hoursExtra: "Hours extra",
          worked: "Worked",
          hoursRegular: "Hours regular",
          breaks: "Breaks",
          novelties: "Novelties",
          workingDay:"Working day",
          generalTotal: "Total general"
        },
        Countrys:{
          co: 'Colombia',
          ve: 'Venezuela',
          us: 'United States'
        },
        About: {
          contactus: 'Contact us',
          nameapp: 'Name app',
          app: 'App'
        },
        Notifications: {
          NAproval: 'N. aproval',
          type: 'Type'
        },
        initialEnroll: {
          title: "Initial enrollment",
          message: "This is enrollment initial",
          continue: "Continue",
          success: "Face enrollment success"
        }
    }
}