export default {
  translations: {
      welcome: "Bienvenido a MyIntelli, ¡Gracias por instalar nuestra app! Ahora podras realizar marcajes usando tu rostro como metodo de autenticacion.Para continuar necesitamos registrar la informacion biometrica de tu rostro.",
      Menu: {
        dashboard: 'Inicio',
        times: 'Tiempos',
        shifts: 'Turnos',
        permits: 'Permisos',
        Setting: 'Ajustes'
      },
      General: {
          date: "Fecha",
          done: "Ok",
          save: "Guardar",
          hour: "Hora",
          search: "Buscar",
          notResult: "Sin resultados",
          close: "Cerrar",
          loading: "Cargando...",
          months: {
            jan: "Enero",
            feb: "Febrero",
            mar: "Marzo",
            apr: "Abril",
            may: "Mayo",
            jun: "Junio",
            july: "Julio",
            aug: "Agosto",
            sept: "Septiembre",
            oct: "Octubre",
            nov: "Noviembre",
            dec: "Diciembre",
          },
          monthsAbv: {
            0: "Ene",
            1: "Feb",
            2: "Mar",
            3: "Abr",
            4: "May",
            5: "Jun",
            6: "Jul",
            7: "Ago",
            8: "Sep",
            9: "Oct",
            10: "Nov",
            11: "Dic",
          },
          daysAbv: {
            0: "Dom",
            1: "Lun",
            2: "Mar",
            3: "Mié",
            4: "Jue",
            5: "Vie",
            6: "Sab",
          },
          in: 'Entrada',
          out: 'Salida',
          fileSizeExceeded: "Tamaño de archivo excedido (20 Mb)",
          hourIn: 'Hora entrada',
          hourOut: 'Hora salida'
      },
      Configuration: {
          changePassword: "Cambiar contraseña",
          currentPassword: "Contraseña Actual",
          newPassword: "Nueva Contraseña",
          validationPassword: "Ingrese la contraseña nuevamente",
          FnLn1: "PRIMER_NOMBRE PRIMER_APELLIDO",
          FnLn1Ln2: "PRIMER_NOMBRE PRIMER_APELLIDO SEGUNDO_APELLIDO",
          FnMnLn1Ln2:
          "PRIMER_NOMBRE SEGUNDO_NOMBRE PRIMER_APELLIDO SEGUNDO_APELLIDO",
          FnMnLn1: "PRIMER_NOMBRE SEGUNDO_NOMBRE PRIMER_APELLIDO",
          Ln1Fn: "PRIMER_APELLIDO PRIMER_NOMBRE",
          Ln1Ln2Fn: "PRIMER_APELLIDO SEGUNDO_APELLIDO PRIMER_NOMBRE",
          Ln1Ln2FnMn:
          "PRIMER_APELLIDO SEGUNDO_APELLIDO PRIMER_NOMBRE SEGUNDO_NOMBRE",
          Ln1FnMn: "PRIMER_APELLIDO PRIMER_NOMBRE SEGUNDO_NOMBRE",
          timeZone: "Zona horaria",
          eventTime: "Hora en eventos",
          formatDate: "Formato de fechas",
          formatHour: "Formato de horas",
          formatNumber: "Formato númerico",
          formatName: "Formato de nombres",
          theme: "Tema",
          notMatchPassword: "Las contraseñas no coinciden",
          timeLocal: "HORA LOCAL",
          timeEvent: "HORA DEL EVENTO",
          "YYYY-MM-DD": "AAAA-MM-DD",
          "DD-MM-YYYY": "DD-MM-AAAA",
          "YYYY/MM/DD": "AAAA/MM/DD",
          "DD/MM/YYYY": "DD/MM/AAAA",
          "MM-DD-YYYY":"MM-DD-YYYY",
          "MM/DD/YYYY":"MM/DD/YYYY",
          kilometres: "Kilómetros",
          miles: "Millas",
      },
      PermissionError: {
          403: "Operación no permitida",
      },
      Common: {
          languageSelect: "Seleccione el idioma",
          configTitle: "Configuración",
          serverInput: "Url del Servidor",
          user: "Usuario",
          save: "Guardar",
          close: "Cerrar",
          restore: "Reestablecer",
          languageTitle: "Idioma",
          restorePassword: "Contraseña",
          forgotPassword: "¿Olvidó Contraseña?",
          copyright: "Derechos Reservados © Intelli Next",
          successTitle: "Operación Exitosa",
          savedSuccess: "Guardado correctamente",
          errorTitle: "Error",
          passwordIncorrect: "Contraseña Incorrecta",
          darkTitle: "Oscuro",
          lightTitle: "Claro",
          passwordResetedSuccesfully: "!Contraseña recuperada exitosamente!",
          recoverySuccess: "Enviado enlace de restablecimiento de contraseña",
          devices: "Dispositivos",
          logout: "Cerrar Sesión",
          search: "Buscar",
          waiting: "Espere",
          updateTitle: "Actualización exitosa",
          uploadedRegister: "Información actualizada con éxito",
          userError: "Usuario y/o contraseña incorrecta",
          notFoundItems: "No se encontraron datos",
          titleFilters: "Filtros",
          accept: "Aceptar",
          cancel: "Cancelar",
          support: "Soporte técnico",
          server: "Servidores",
          device: "Dispositivo",
          formatDate: "Formato de fecha",
          formatHour: "Formato de tiempo",
          formatNumber: "Formato numerico",
          formatLength: "Formato de longitud",
          formatTemperature: "Formato de temperatura",
          timeZone: "Zona horaria",
          about: "Acerca de",
          yes: "Sí",
          no: "No",
          logOut: "Cerrar sesión",
          sureLogOut: "¿Está seguro de que desea Cerrar la sesión?",
          settings: "Ajustes",
          notifications: "Notificaciones",
          other: 'Otro',
          urlserver: 'URL servidor',
          time: 'Horarios',
          informationTurn: 'Información de horario',
          alert: 'Alerta',
          inConstruction: 'En contrucción',
          comingSoon: 'Próximamente disponible',
          today: 'Hoy',
          notFaceDetected:"Rostro no detectado",
          permissionDetails: 'Detalle del permiso',
          permissions: 'Permisos',
          timelogs:"Marcajes",
          selectedTypePerson: 'Seleccionar Tipo de persona',
          schedules: 'Horarios',
          titleConfirm: 'Confirmación de eliminación',
          confirmDelete: '¿Está seguro de eliminar?',
          deletedSuccess: 'Eliminación exitosa',
          now: 'Ahora',
          warning: "Advertencia",
          uploadedRegister: "Actualización exitosa",
          see: 'Ver',
          details: 'Detalles',
          punch: 'Marcaje',
          punchesHistory: 'Historial de Marcajes',
          successTimelogNew : "Marcaje realizado con éxito",
          later: "Preguntame después",
          warnings: {
            notActiveGPS: "El GPS no se encuentra activo",
            notLocationGet: "No se pudo obtener la ubicación",
            locationMessage: "No está autorizado para obtener la ubicación",
            notPermissionCamera: "Active los permisos para usar la camara",
            notPermissionGPS: "Active los permisos para usar la ubicación"
          },
          permission:{
            cameraTitle: "Permisos de camara",
            cameraMessage: "Para realizar está operación se requiere el uso de la camara",
            gpsTitle: "Permisos de ubicación",
            gpsMessage: "Para realizar está operación se requiere el uso de la ubicación"
          },
          delete: 'ELIMINAR',
          mainServer: 'Servidor principal',
          notTimelog:"No se encontraron marcaciones"
      },
      Login: {
          email: "Correo Electrónico:",
          placeholderEmail: "Ingrese el correo electrónico",
          password: "Contraseña:",
          placeholderPassword: "Ingrese su contraseña",
          signIn: "Ingresar",
      },
      Errors: {
          user_blocked: "El usuario se encuentra bloqueado, intente recuperar contraseña",
          userError: "Usuario y/o contraseña incorrecta",
          disabledUser: "El usuario se encuentra inactivo",
          userBlocked: "El usuario se encuentra bloqueado, intente recuperar contraseña",
          tokenExpired: "Su sesión ha expirado",
          invalidPassword: "Contraseña inválida",
          serverDown: "Conexión fallida!",
          notDeletedEntity: 'La entidad no puede ser eliminada, 1 o mas registros asociados',
          INVALID_DATE_IN: "Fecha inválida - Fecha final menor a la inicial",
          ENTITY_NOT_FOUND: "No se encontró la entidad",
          ENTITY_DONT_HAVE_CONTRACT: "La entidad no posee contrato",
          INVALID_DATE_FOR_PERIOD: "Período de nómina cerrado",
          INVALID_DATE_ENTITY_HAVE_PERMISSION:
            "La entidad ya posee un permiso para la fecha indicada",
          INVALID_DATE_ENTITY_HAVE_SCHEDULE:
              "La entidad ya posee un horario para la fecha indicada",
          personExistPhoto: "Rostro ya enrolado",
          personPhotoNotBelongTo: "El rostro no pertenece a la persona",
          personPhotoThereAreNoFaces: "No se detectan rostros en la foto",
          personPhotoMoreThanOneElementExits: "Existe mas de un rostro en la foto",
          invalid:"Error desconocido"
      },
      FormErrors: {
          if111: 'Campo requerido',
          if112: 'Campo único',
          if112B: 'El registro esta siendo utilizado',
          if113: 'Campo de tipo entero',
          if114: 'Longitud máxima del campo excedida',
          if115: 'Longitud mínima del campo no alcanzada',
          if116: 'Correo electrónico inválido',
          if117: 'Campo de tipo arreglo',
          if118: 'Valor inválido',
          if119: 'Campo de tipo caracter',
          if120: 'Ya se encuentra registrado',
          if121: 'Campo debe ser entero',
          if122: 'La estructura debe ser una puerta o un control de acceso',
          if123: 'No se permite espacios en blanco',
          if124: 'La estructura debe permitir parqueaderos',
          if125: 'Las contraseñas ingresadas no coinciden',
          if126: 'URL inválida',
          if130: 'El nuevo tipo agregado ya existe para la persona',
          if132: 'Fecha/hora exceden el rango',
          if404: 'Campo no existe',
          if492: 'No puede ser estructura organizactiva, 1 o más dispositivos asignados',
          STATUS_CONFLICT: 'Estructura de tipo organizacional no puede contener estructuras físicas',
          if133: 'Aun tiene 1 cargo sin asignar',
          if134: 'Cantidad debe ser mayor a 0',
          if135: 'ReCaptcha invalido',
          dateOutBeforeDateIn: 'Fecha final no puede ser anterior a la fecha inicial',
          dateInBeforeNow: 'Fecha inicial no puede ser mayor a hoy',
          dateVistBeforeNow: 'Fecha de la visita no puede ser anterior a hoy',
          hourVistBeforeNow: 'Hora de la visita no puede ser inferior a la actual',
          datesOutOfInitialRange: 'Fecha/hora exceden el rango',
            
      },
      User: {
          user: 'Usuario',
          fullName: 'Nombre completo',
          dni: 'C.C',
          email: 'Correo electrónico',
          cel: 'Teléfono',
          dataNotRegistered: 'DATO NO REGISTRADO',
          position: "Cargo",
          job: "Trabajo",
          localization: "Localización",
          user: "Nombre",
          active: 'Activo',
          activate: 'Activar',
          profilePicture: 'Foto de perfil',
          enrollFace: 'Enrolar rostro',
          personalInformation: 'Datos personales'
      },
      ChangePassword: {
          currentPassword: "Contraseña actual",
          newPassword: "Nueva contraseña",
          validationPassword: "Ingrese la contraseña nuevamente",
      },
      Support: {
          email: 'Correo electrónico:',
          cellphones: 'Teléfono:',
          userManual: "Manual de usuario:",
          address: 'Dirección:'
      },
      Device: {
          device: 'Dispositivo:',
          key: 'Key:',
          os: 'Sistema operativo',
          enroll: 'Enrolar',
          enrolled: 'Enrolado',
      },
      Vehicle: {
          vehicle_plate: "Placa",
      },
      EventTask: {
          text_to_send: "Texto a enviar",
          eventTypeCommon: "Común",
          // Paginas
          event: "Evento",
          actions: "Acciones",
          newAction: "Nueva Acción",
  
          // Modulos
          general: "General",
          access_control: "Control de Acceso",
          visits: "Visitantes",
          devices: "Dispositivos",
          users: "Usuarios",
          notifications: "Notificaciones",
          system: "Sistema",
          time_attendance: "Tiempo y asistencia",
  
          // Etiquetas/Placeholders
          event_name: "Nombre del evento",
          type_event_monitor: "¿Qué tipo de evento desea supervisar?",
          want_monitor: "¿Qué desea supervisar?",
          select_type_filters: "Seleccione los tipos de filtros",
          select_module: "Seleccione el módulo",
          type_action_do: "¿Qué tipo de acción quiere realizar?",
          select_parameters: "Seleccionar parámetros de acción",
  
          // Eventos/Acciones
          ip: "Dirección ip",
  
          action_scheduled: "Acción Programada",
          scheduled_action: "Acción programada",
          timelog: "Marcaje",
          timelog_ac_accepted: "Marcaje Verificado",
          timelog_ta_accepted: "Marcaje Verificado",
          inTimeLog: "MARCAJE DE ENTRADA",
          outTimeLog: "MARCAJE DE SALIDA",
          inAndOutTimelog: "MARCAJE DE ENTRADA / SALIDA",
          disabledTimelog: "MARCAJE INHABILITADO",
          firstTimeLog: "PRIMER MARCAJE",
          timelog_ac_not_verified: "Marcaje no Verificado",
          timelog_ta_not_verified: "Marcaje no Verificado",
          invalidTimelog: "MARCAJE INVALIDO",
          delayTimeLog: "MARCAJE CON TARDANZA tardanza",
          open_exit_button: "Apertura con Botón de Salida",
          access_scheduled: "Horario de Acceso",
          scheduled_access: "Horario de Acceso",
          change_status_door_remote: "Cambio Remoto de Estado en Puerta",
          change_status_door_manual: "Cambio Manual de Estado en Puerta",
          visit_new: "Nueva Visita",
          visit_new_scheduled: "Nueva Visita Programada",
          visit_closed: "Visita Cerrada",
          visit_change_status_scheduled: "Cambio de Estado en Visita Programada",
          change_access_profile_persons: "Cambiar perfil de acceso de personas",
          change_access_profile_vehicles: "Cambiar perfil de acceso de vehículos",
          add_to_blacklist: "Agregar a lista negra",
          remove_from_blacklist: "Remover de lista negra",
          connection_change: "Cambio de Conexión",
          user_login: "Inicio de Sesión de usuario",
          user_creation: "Creación de Usuario",
          user_blocked: "Bloqueo de Usuario",
          password_change: "Cambio de Contraseña",
          reports: "Reportes",
          open_door: "Abrir Puertas",
          close_door: "Cerrar Puertas",
          lock_door: "Bloquear Puertas",
          access_scheduled_enabled: "Habilitar Horarios de Acceso",
          access_scheduled_disabled: "Deshabilitar Horarios de Acceso",
          inactivate_person: "Inactivar personas",
          activate_person: "Activar personas",
          inactivate_vehicles: "Inactivar Vehículos",
          activate_vehicles: "Activar Vehículos",
          change_access_role: "Deshabilitar Personas/Vehículos",
          persons_vehicles_disabled: "Cambio Perfil de Acceso",
          inactivate_registration_station: "Inactivar Estaciones de Trabajo",
          activate_registration_station: "Activar Estaciones de Trabajo",
          blacklist_goto: "Pasar a Lista Negra",
          inactivate_device: "Inactivar dispositivos",
          activate_device: "Activar dispositivos",
          alerts: "Alertas",
          widgets: "Widgets",
          text_messages: "Mensajes de Texto",
          email_messages: "Mensajes de Correo",
          plans: "Planos",
          battery_status_change: "Cambio de estado de batería",
          based_event: "Basado en el evento",
          create_update_user: "Modificaciones de usuario",
  
          // Filtros y Parámetros
          all_person: "Todas las personas",
          all_vehicle: "Todos los vehículos",
          entities: "Personas",
          entity: "Entidad",
          entities_types: "Tipos de personas",
          device: "Dispositivo",
          structures: "Estructuras",
          time: "Tiempo",
          vehicles: "Vehículos",
          vehicle_type: "Tipo de vehículo",
          biometric_models: "Módelos de biométricos",
          verification_modes: "Modos de verificación",
          start: "Inicio",
          end: "Final",
          start_end: "¿En el momento de?",
          user: "Usuario",
          visitants: "Visitantes",
          visitors: "Visitantes",
          visited: "Visitados",
          access_roles: "Perfil de acceso",
          work_stations: "Estaciones de trabajo",
          report_templates: "Plantillas de reportes",
          execution_time: "Momento de ejecución",
          weekdays: "Días de la semana",
          devices_types: "Tipos de dispositivos",
          device_status: "Estado de dispositivos",
          door_status: "Estado de puertas",
          scheduled_visit_status: "Estado de visitas programadas",
          closing_mode_status: "Modo de cierre",
          connected: "Conectado",
          disconnected: "Desconectado",
          open: "Abrir",
          close: "Cerrar",
          lock: "Bloquear",
          executed: "Ejecutada",
          cancelled: "Cancelada",
          automatic: "Automática",
          manual: "Manual",
          report_templates: "Plantillas de reportes",
          user_defined: "Definido por usuario",
          emails: "Correos",
          emailsPlaceholder: "ejemplo@correo.com",
          recurrence_value: "Valor de recurrencia",
          text_messaging_templates: "Plantillas SMS",
          // text_messaging_templates: 'Plantillas de Mensjes de Texto',
          based_on_event: "Basado en el evento",
          access_types: "Tipos de accesos",
          verification_results: "Resultados de verificación",
          persons_groups: "Grupos de personas",
          devices_groups: "Grupos de dispositivos",
          vehicles_groups: "Grupos de vehículos",
          battery_status: "Estado de batería",
  
          // Campos
          field_in_date: "Fecha inicial",
          field_out_date: "Fecha final",
          field_in_hour: "Hora inicial",
          field_out_hour: "Hora final",
          field_status: "Estatus",
          field_event_name: "Nombre del evento",
          field_settings_type: "Tipo de configuracion",
          field_supervise: "Supervisando",
          field_filters: "Filtros",
          field_entities: "Personas",
          field_entities_types: "Tipos de personas",
          field_devices: "Dispositivos",
          field_structures: "Estructuras",
          field_dow: "Días de la semana",
          field_in_hour: "Hora inicial",
          field_out_hour: "Hora final",
          field_status: "Estatus",
          field_vehicles: "Vehículos",
          field_plate: "Placa",
          field_users: "Usuarios",
          field_visitants: "Visitantes",
          field_devices_models_biometrics: "Modelos de biométricos",
          field_verification_modes: "Modos de verificación",
          field_access_scheduled: "Horario de Acceso",
          field_start_end: "¿En el momento de?",
          field_access_roles: "Roles de acceso",
          field_work_stations: "Estaciones de trabajo",
          field_execute_hour: "Hora de ejecución",
          field_device_types: "Tipos de dispositivos",
          field_access_type: "Tipos de acceso",
          field_visiteds: "Visitados",
          field_verification_result: "Resultado de verificación",
          field_vehicles_types: "Tipos de vehículos",
          field_filter_status: "Estados de dispositivos",
          field_common_action: "Accion común",
          field_module: "Módulo",
          field_icons_groups: "Grupos de iconos",
          field_entities_groups: "Grupos de personas",
          field_devices_groups: "Grupos de dispositivos",
          field_vehicles_groups: "Grupos de vehículos",
          field_based_on_event: "Basado en el evento",
          field_repetitions: "Repeticiones",
          field_recurrence: "Recurrencia",
          field_parameters: "Parámetros",
          field_phones: "Teléfonos",
          field_emails: "Correos Electrónicos",
          field_time_delay: "Tiempo de retardo",
          field_access_profiles: "Perfiles de acceso",
          field_time_hour: "Hora",
          field_content_text: "Texto contenido",
          field_id_text_template: "Id plantilla de texto",
  
          // triggered_at: 'Hora del evento',
          // event_description: 'Descripcion del evento',
          eventTypes: "Tipo de evento",
          // eventAction: 'Acción a realizar',
          // eventHeld: 'Acción realizada',
          // events: 'Eventos',
          persons_event: "Seleccione las personas involucradas",
          // devices_event: 'Dispositivos',
          // device: 'Dispositivo',
          // structure: 'Estructura',
          // settingsTypeIn: 'Desde',
          // settingsTypeOut: 'Hasta',
          // type: 'Tipo',
          // category: 'Categoria',
          // actions: 'Acciones',
          // typeNotification: 'Tipo de notificación',
          // actionDevices: 'Acciones del dispositivo',
          // sendType: 'Prioridad del envio',
          // email: 'Correos',
          // phone: 'Teléfonos',
          // hourAction: 'Hora de envio',
          status: "Estado",
          // emergencyAlarm: 'ALARMA DE EMERGENCIA',
          // fireAlarm: 'ALARMA DE INCENDIO',
          // securityAlarm: 'ALARMA DE SEGURIDAD',
          // sysmicAlarm: 'ALARMA SISMICA',
          // sendMoment: 'ENVIAR AL MOMENTO',
          // sendSpecificTime: 'ENVIAR EN UN TIEMPO DETERMINADO',
          // notificationBar: 'NOTIFICACIÓN EN BARRA SUPERIOR',
          // alertMessage: 'Mensaje de alerta',
          // devices: 'Dispositivo a Accionar',
          // simpleNotification: 'NOTIFICACIÓN SIMPLE',
          // activeAlarm: 'ACTIVAR ALARMA',
          // turnOnLight: 'ENCENDER LUZ',
          // turnOffLight: 'APAGAR LUZ',
          // sendEmail: 'ENVIAR CORREO ELECTRÓNICO',
          // sendSms: 'ENVIAR SMS',
          // openDoor: 'APERTURAR PUERTA',
          // widgetNotification: 'WIDGET DE NOTIFICACIÓN',
          // soundedAlarm: 'INTRUSIÓN DE ZONA',
          // anyone: 'CUALQUIERA',
          // emergencyLight: 'LUZ DE EMERGENCIA',
          // nightLight: 'LUZ NOCTURNA',
          // backupLight: 'LUZ DE RESPALDO',
          // Entities_types: 'Tipos de persona',
          // emails: 'Correos',
          phones: "Teléfonos",
          // dashboardTimelogs: 'DASHBOARD CONTROL DE ACCESO',
          // dashboardVisit: 'DASHBOARD CONTROL DE VISITANTE',
          // visitTimelogs: 'MARCAJES DE VISITANTES',
          createOrUpdateUser: {
            2: "NUEVO USUARIO",
            3: "ACTUALIZACIÓN DE USUARIO",
          },
  
          //LIST
          label_module: "Módulo",
          label_event_type: "Tipo de Evento",
          label_supervising: "Supervisando",
          label_filters: "Filtros",
          label_parameters: "Parametros",
          label_event_action: "Acción",
          label_structures: "Estructuras",
          label_devices: "Dispositivos",
          label_devices_models: "Modelos de dispositivos",
          label_not_has_elements: "No tiene información",
          infoEvent: "Información del evento",
          infoActions: "Acciones del evento",
          infoAction: "Información de la acción",
          recurenceDaily: "Diaria",
          recurenceWeekly: "Semanal",
          label_execute_time: "Tiempo de ejecución",
          label_minutes: "Minutos",
          label_elements: "Elementos",
          label_select_recurrence: "Recurrencia",
          label_repetitions: "Repeticiones",
  
          label_async_entities: "¿Cuáles personas?",
          label_async_entities_types: "¿Cuáles son los tipos de personas?",
          label_async_vehicles: "¿Cuáles vehículos?",
          label_async_vehicles_types: "¿Cuáles son los tipos de vehículos?",
          label_async_access_scheduled: "¿Cuáles horarios de acceso?",
          label_async_access_profiles: "¿Cuáles perfiles de acceso?",
          label_async_work_stations: "¿En qué Estaciones de trabajo?",
          label_async_users: "¿Cuáles usuarios?",
          label_async_visitants: "¿Cuáles visitantes?",
          label_async_Visiteds: "¿Cuáles visitados?",
          label_async_devices: "¿En qué dispositivos?",
          label_async_content_report:
            "¿Qué tipo de contenido llevara el reporte?",
          label_async_content_text: "¿Qué tipo de contenido llevara el mensaje?",
          label_async_persons_groups: "¿En qué grupo de personas?",
          label_async_devices_groups: "¿En qué grupo de dispositivos?",
          label_async_vehicles_groups: "¿En qué grupo de vehículos?",
          label_devices_types: "¿Cuáles son los tipos de dispositivos?",
          label_devices_models: "¿Cuáles modelos de dispositivos?",
          label_access_types: "¿Cuáles son los tipos de acceso?",
          label_verifications_modes: "Seleccione los modos de verificacion",
          label_verifications_result: "Seleccione el resultado de verificacion",
          label_close_modes: "Defina el modo de cierre de la visita",
          label_what_time: "¿En qué momento?",
          label_defined_status: "Defina el estado",
          label_set_time: "Cuando ocurre entre",
          label_structure_event: "¿En qué estructuras?",
          label_structure_action: "¿En qué estructuras?",
          label_recurrence: "Valor de Recurrencia",
          limitActions: "No puede eliminar, limite minimo de 1 accion por evento",
          visit_timelogs: "Marcajes de visitantes",
          plan_notification: "Notificaciones en plano",
          change_status_message:
            "¿Está seguro de que desea cambiar el estado del registro?",
          change_status: "Cambiar estatus",
  
          //Items
          executeTime: {
            1: "Inmediato",
            2: "Retardo",
            3: "Específico",
          },
          recurrenceType: {
            1: "Diario",
            2: "Semanal",
          },
          result: {
            0: "Exitoso",
            1: "Inválido",
          },
          495: "No puede eliminar eventos comunes",
        },
        DetailTimelog: {
          title: "Detalle del marcaje",
          in: "Entrada",
          out: "Salida",
          verified: "Verificado",
          notVerified: "No verificado",
          sendTimelog: "ENVIAR",
          cancelTimelog: "Cancelar envio",
          turn: 'Turno',
          localization: 'Localización',
          job: 'Trabajo',
          hour: 'Hora',
          timelog:'Marcaje'
        },
        Turn: {
          week: 'S',
          biweekly: 'Q',
          monthly: 'M',
          date: 'Fecha',
          turn: 'Turno',
          turns: 'Turnos',
          hour: 'Horas',
          hours: 'Horas',
          localization: 'Localización',
          job: 'Trabajo',
          since: "Desde",
          until: "Hasta",
          unscheduled: 'Sin programación',
          permission: "Permiso",
          Files: "Archivos",
          notTurn: "No se encontraron turnos"
        },
        Permission: {
          level1: "APROBADO",
          level2: "RECHAZADO",
          level3: "VERIFICADO",
          level4: "EN PETICIÓN",
          level5: "FLOTANTE",
          level6: "FLOTANTE",
          type: 'Tipo',
          hour: 'Hora',
          description: 'Descripción',
          status: "Estatus",
          Files: "Archivo",
          date: 'Fecha',
          history: "Histórico",
          type_parcial: "PARCIAL",
          type_daily: "DIARIO",
          newPermission: 'Nuevo permiso',
          editPermission: 'Editar permiso',
          dateIn: 'Fecha inicio',
          dateOut: 'Fecha fin',
          timeIn: 'Hora de inicio',
          timeOut: 'Hora final',
          id_novelty_permission: 'Novedad o permiso',
          date_time_in: 'Fecha inicial',
          date_time_out: "Fecha final",
          time_in: "Hora de inicio",
          time_out: "Hora final",
          notPermission: "No se encontraron permisos"
        },
        Times: {
          title: 'Tiempos',
          withoutPunch: 'Sin marcaje',
          notScheduled: "Sin horario",
          resumeHours: "Resumen de tiempos",
          hoursScheduled: "Horas programadas",
          hoursWorking: "Horas trabajadas",
          hoursExtra: "Horas extras",
          worked: "Trabajado",
          hoursRegular: "Horas ordinarias",
          breaks: "Descanso",
          novelties: "Novedades",
          workingDay:"Detalle de la jornada",
          generalTotal: "Total general"
        },
        Countrys:{
          co: 'Colombia',
          ve: 'Venezuela',
          us: 'Estados Unidos'
        },
        About: {
          contactus: 'Contáctenos',
          nameapp: 'Nombre de aplicación',
          app: 'Aplicación móvil'
        },
        Notifications: {
          NAproval: 'N. aprobación',
          type: 'Tipo'
        },
        initialEnroll: {
          title: "Enrolamiento inicial",
          message: "Este es el enrolamiento inicial",
          continue: "Continuar",
          success: "Rostro enrolado con éxito"
        }
  },
}